DROP TABLE PLASMODB.TEMPEXPORTDB2;

CREATE TABLE PLASMODB.TEMPEXPORTDB2 
  (SOURCE_ID  VARCHAR(50),
   CONSTRAINT TEMPEXPORTDB2_PK PRIMARY KEY (SOURCE_ID));
   
INSERT INTO PLASMODB.TEMPEXPORTDB2
  SELECT SOURCE_ID
    FROM 
	  (SELECT source_id, ROWNUM num
	    FROM
	      (SELECT SOURCE_ID
		     FROM DOTS.GENEFEATURE G
			 ORDER BY na_feature_id DESC)
	   )
    WHERE NUM > 1000 AND NUM < 1030;
    
INSERT INTO PLASMODB.TEMPEXPORTDB2 VALUES ('MAL8P1.79');
INSERT INTO PLASMODB.TEMPEXPORTDB2 VALUES ('PF11_0338');
INSERT INTO PLASMODB.TEMPEXPORTDB2 VALUES ('MAL13P1.118');
INSERT INTO PLASMODB.TEMPEXPORTDB2 VALUES ('PB000914.03.0');
INSERT INTO PLASMODB.TEMPEXPORTDB2 VALUES ('MAL13P1.227');
INSERT INTO PLASMODB.TEMPEXPORTDB2 VALUES ('MAL13P1.205');
    
COMMIT;

exit;