

/* Schema REFSEQ */

CREATE SCHEMA REFSEQ;

CREATE TABLE REFSEQ.CATALOG 
(
   GI INTEGER NOT NULL,
   ACC VARCHAR(40),
   TAX_ID INTEGER,
   SEQ VARCHAR(500),
   CONSTRAINT CATALOG_PK PRIMARY KEY (GI)
);

CREATE TABLE REFSEQ.SPECIES 
(
   TAX_ID INTEGER NOT NULL,
   SPECIES VARCHAR(300),
   CONSTRAINT SPECIES_PK PRIMARY KEY (TAX_ID)
);

CREATE TABLE REFSEQ.RMVRECORDS  
(
   GI INTEGER NOT NULL,
   ACC VARCHAR(40),
   TAX_ID INTEGER,
   SEQ VARCHAR(500),
   REPLACEDBY INTEGER,
   CONSTRAINT CATALOG_PK PRIMARY KEY (GI)
);

CREATE TABLE REFSEQ.CATALOG_L
(
   GI INTEGER NOT NULL,
   ACC VARCHAR(40),
   TAX_ID INTEGER,
   SEQ VARCHAR(500),
   CONSTRAINT CATALOG_PK PRIMARY KEY (GI)
);
 
CREATE TABLE REFSEQ.CATALOG_R
(
   GI INTEGER NOT NULL,
   ACC VARCHAR(40),
   TAX_ID INTEGER,
   SEQ VARCHAR(500),
   CONSTRAINT CATALOG_PK PRIMARY KEY (GI)
);


CREATE TABLE REFSEQ.RMVRECORDS_L  
(
   GI INTEGER NOT NULL,
   ACC VARCHAR(40),
   TAX_ID INTEGER,
   SEQ VARCHAR(500),
   REPLACEDBY INTEGER,
   CONSTRAINT CATALOG_PK PRIMARY KEY (GI)
);

CREATE TABLE REFSEQ.RMVRECORDS_R
(
   GI INTEGER NOT NULL,
   ACC VARCHAR(40),
   TAX_ID INTEGER,
   SEQ VARCHAR(500),
   REPLACEDBY INTEGER,
   CONSTRAINT CATALOG_PK PRIMARY KEY (GI)
);


CREATE TABLE REFSEQ.SPECIES_L
(
   TAX_ID INTEGER NOT NULL,
   SPECIES VARCHAR(300),
   CONSTRAINT SPECIES_PK PRIMARY KEY (TAX_ID)
);

CREATE TABLE REFSEQ.SPECIES_R
(
   TAX_ID INTEGER NOT NULL,
   SPECIES VARCHAR(300),
   CONSTRAINT SPECIES_PK PRIMARY KEY (TAX_ID)
);

/** Schema TAXONOMY */
CREATE SCHEMA TAXO;

CREATE TABLE TAXO.NAMES 
(
   TAX_ID INTEGER NOT NULL,
   NAME VARCHAR(500) NOT NULL,
   NAME_CLASS VARCHAR(300) NOT NULL,
   CONSTRAINT CST_NAMES_PK PRIMARY KEY (TAX_ID, NAME, NAME_CLASS)
);

CREATE TABLE TAXO.NAMES_L 
(
   TAX_ID INTEGER NOT NULL,
   NAME VARCHAR(500) NOT NULL,
   NAME_CLASS VARCHAR(300) NOT NULL,
   CONSTRAINT CST_NAMES_PK PRIMARY KEY (TAX_ID, NAME, NAME_CLASS)
);

CREATE TABLE TAXO.NAMES_R
(
   TAX_ID INTEGER NOT NULL,
   NAME VARCHAR(500) NOT NULL,
   NAME_CLASS VARCHAR(300) NOT NULL,
   CONSTRAINT CST_NAMES_PK PRIMARY KEY (TAX_ID, NAME, NAME_CLASS)
);
