CONNECT TO BIOTB USER db2 USING xxx;

DELETE FROM PLASMO.GENEFEAT_L_INS;
IMPORT FROM outFiles/pcbi_plasmo_genefeat.txt OF DEL MODIFIED BY COLDEL|
	METHOD P (1, 2, 3) MESSAGES NUL 
	INSERT INTO PLASMO.GENEFEAT_L_INS (SRC_ID, PRODUCT, REFSEQ_ACC);
RUNSTATS ON TABLE PLASMO.GENEFEAT_L_INS ON ALL COLUMNS ALLOW WRITE ACCESS;

DELETE FROM PLASMO.GENEFEAT;
IMPORT FROM outFiles/pcbi_plasmo_genefeat.txt OF DEL MODIFIED BY COLDEL|
	METHOD P (1, 2, 3) MESSAGES NUL 
	INSERT INTO PLASMO.GENEFEAT (SRC_ID, PRODUCT, REFSEQ_ACC);
RUNSTATS ON TABLE PLASMO.GENEFEAT ON ALL COLUMNS ALLOW WRITE ACCESS;

DELETE FROM PLASMO.GENETAX_L_INS;
IMPORT FROM outFiles/pcbi_plasmo_genetax.txt OF DEL MODIFIED BY COLDEL|
	METHOD P (1, 2) MESSAGES NUL 
	INSERT INTO PLASMO.GENETAX_L_INS (SRC_ID, TAX_ID);
RUNSTATS ON TABLE PLASMO.GENETAX_L_INS ON ALL COLUMNS ALLOW WRITE ACCESS;

DELETE FROM PLASMO.GENETAX;
IMPORT FROM outFiles/pcbi_plasmo_genetax.txt OF DEL MODIFIED BY COLDEL|
	METHOD P (1, 2) MESSAGES NUL 
	INSERT INTO PLASMO.GENETAX (SRC_ID, TAX_ID);
RUNSTATS ON TABLE PLASMO.GENETAX ON ALL COLUMNS ALLOW WRITE ACCESS;


DELETE FROM PLASMO.DOMAIN_REF_L_INS;
IMPORT FROM outFiles/pcbi_plasmo_domainref.txt OF DEL MODIFIED BY COLDEL|
	METHOD P (1, 2, 3) MESSAGES NUL 
	INSERT INTO PLASMO.DOMAIN_REF_L_INS (SRC_ID, DB, DBACC);
RUNSTATS ON TABLE PLASMO.DOMAIN_REF_L_INS ON ALL COLUMNS ALLOW WRITE ACCESS;

DELETE FROM PLASMO.DOMAIN_REF;
IMPORT FROM outFiles/pcbi_plasmo_domainref.txt OF DEL MODIFIED BY COLDEL|
	METHOD P (1, 2, 3) MESSAGES NUL 
	INSERT INTO PLASMO.DOMAIN_REF (SRC_ID, DB, DBACC);
RUNSTATS ON TABLE PLASMO.DOMAIN_REF ON ALL COLUMNS ALLOW WRITE ACCESS;



DELETE FROM REFSEQ.CATALOG_L_INS;
IMPORT FROM outFiles/ncbi_refseq_catalog.txt OF DEL MODIFIED BY COLDEL|
	METHOD P (1, 2, 3, 4) MESSAGES NUL 
	INSERT INTO REFSEQ.CATALOG_L_INS (GI, ACC, TAX_ID, SEQ);
RUNSTATS ON TABLE REFSEQ.CATALOG_L_INS ON ALL COLUMNS ALLOW WRITE ACCESS;


DELETE FROM REFSEQ.CATALOG;
IMPORT FROM outFiles/ncbi_refseq_catalog.txt OF DEL MODIFIED BY COLDEL|
	METHOD P (1, 2, 3, 4) MESSAGES NUL 
	INSERT INTO REFSEQ.CATALOG (GI, ACC, TAX_ID, SEQ);
RUNSTATS ON TABLE REFSEQ.CATALOG ON ALL COLUMNS ALLOW WRITE ACCESS;


DELETE FROM REFSEQ.RMVRECORDS_L_INS;
IMPORT FROM outFiles/ncbi_refseq_rmvrecords.txt OF DEL MODIFIED BY COLDEL|
	METHOD P (1, 2, 3, 4, 5) MESSAGES NUL 
	INSERT INTO REFSEQ.RMVRECORDS_L_INS (GI, ACC, TAX_ID, SEQ, REPLACEDBY);
RUNSTATS ON TABLE REFSEQ.RMVRECORDS_L_INS ON ALL COLUMNS ALLOW WRITE ACCESS;

DELETE FROM REFSEQ.RMVRECORDS;
IMPORT FROM outFiles/ncbi_refseq_rmvrecords.txt OF DEL MODIFIED BY COLDEL|
	METHOD P (1, 2, 3, 4, 5) MESSAGES NUL 
	INSERT INTO REFSEQ.RMVRECORDS (GI, ACC, TAX_ID, SEQ, REPLACEDBY);
RUNSTATS ON TABLE REFSEQ.RMVRECORDS ON ALL COLUMNS ALLOW WRITE ACCESS;



DELETE FROM TAXO.NAMES_L_INS;
IMPORT FROM outFiles/ncbi_taxo_names.txt OF DEL MODIFIED BY COLDEL|
	METHOD P (1, 2, 3) MESSAGES NUL 
	INSERT INTO TAXO.NAMES_L_INS (TAX_ID, NAME, NAME_CLASS);
RUNSTATS ON TABLE TAXO.NAMES_L_INS ON ALL COLUMNS ALLOW WRITE ACCESS;

DELETE FROM TAXO.NAMES;
IMPORT FROM outFiles/ncbi_taxo_names.txt OF DEL MODIFIED BY COLDEL|
	METHOD P (1, 2, 3) MESSAGES NUL 
	INSERT INTO TAXO.NAMES (TAX_ID, NAME, NAME_CLASS);
RUNSTATS ON TABLE TAXO.NAMES ON ALL COLUMNS ALLOW WRITE ACCESS;



DELETE FROM GO.TERM_L_INS;
IMPORT FROM outFiles/go_term.txt OF DEL MODIFIED BY COLDEL|
	METHOD P (1, 2, 3) MESSAGES NUL 
	INSERT INTO GO.TERM_L_INS (ID, NAME, ACC);
RUNSTATS ON TABLE GO.TERM_L_INS ON ALL COLUMNS ALLOW WRITE ACCESS;

DELETE FROM GO.TERM;
IMPORT FROM outFiles/go_term.txt OF DEL MODIFIED BY COLDEL|
	METHOD P (1, 2, 3) MESSAGES NUL 
	INSERT INTO GO.TERM (ID, NAME, ACC);
RUNSTATS ON TABLE GO.TERM ON ALL COLUMNS ALLOW WRITE ACCESS;



DELETE FROM INTERPRO.ENTRY_L_INS ;
IMPORT FROM outFiles/ebi_interpro_entry.txt OF DEL MODIFIED BY COLDEL|
	METHOD P (1, 2) MESSAGES NUL 
	INSERT INTO INTERPRO.ENTRY_L_INS  (ENTRY_AC, NAME);
RUNSTATS ON TABLE INTERPRO.ENTRY_L_INS ON ALL COLUMNS ALLOW WRITE ACCESS;

DELETE FROM INTERPRO.ENTRY ;
IMPORT FROM outFiles/ebi_interpro_entry.txt OF DEL MODIFIED BY COLDEL|
	METHOD P (1, 2) MESSAGES NUL 
	INSERT INTO INTERPRO.ENTRY  (ENTRY_AC, NAME);
RUNSTATS ON TABLE INTERPRO.ENTRY ON ALL COLUMNS ALLOW WRITE ACCESS;


DELETE FROM INTERPRO.ENTRY2METH_L_INS ;
IMPORT FROM outFiles/ebi_interpro_entry2meth.txt OF DEL MODIFIED BY COLDEL|
	METHOD P (1, 2, 3) MESSAGES NUL 
	INSERT INTO INTERPRO.ENTRY2METH_L_INS  (ENTRY_AC, METHOD_AC, DB);
RUNSTATS ON TABLE INTERPRO.ENTRY2METH_L_INS ON ALL COLUMNS ALLOW WRITE ACCESS;

DELETE FROM INTERPRO.ENTRY2METH ;
IMPORT FROM outFiles/ebi_interpro_entry2meth.txt OF DEL MODIFIED BY COLDEL|
	METHOD P (1, 2, 3) MESSAGES NUL 
	INSERT INTO INTERPRO.ENTRY2METH  (ENTRY_AC, METHOD_AC, DB);
RUNSTATS ON TABLE INTERPRO.ENTRY2METH ON ALL COLUMNS ALLOW WRITE ACCESS;


DELETE FROM INTERPRO.INTERPRO2GO_L_INS ;
IMPORT FROM outFiles/ebi_interpro_interpro2go.txt OF DEL MODIFIED BY COLDEL|
	METHOD P (1, 2) MESSAGES NUL 
	INSERT INTO INTERPRO.INTERPRO2GO_L_INS  (ENTRY_AC, GO_AC);
RUNSTATS ON TABLE INTERPRO.INTERPRO2GO_L_INS ON ALL COLUMNS ALLOW WRITE ACCESS;

DELETE FROM INTERPRO.INTERPRO2GO ;
IMPORT FROM outFiles/ebi_interpro_interpro2go.txt OF DEL MODIFIED BY COLDEL|
	METHOD P (1, 2) MESSAGES NUL 
	INSERT INTO INTERPRO.INTERPRO2GO  (ENTRY_AC, GO_AC);
RUNSTATS ON TABLE INTERPRO.INTERPRO2GO ON ALL COLUMNS ALLOW WRITE ACCESS;


COMMIT WORK;
DISCONNECT ALL;
