
CREATE SCHEMA GO;

CREATE TABLE GO.TERM 
(
  ID INTEGER NOT NULL,
  NAME VARCHAR(255),
  ACC VARCHAR(255),
  CONSTRAINT TERM_PK PRIMARY KEY (ID)
);

CREATE TABLE GO.TERM_L
(
  ID INTEGER NOT NULL,
  NAME VARCHAR(255),
  ACC VARCHAR(255),
  CONSTRAINT TERM_PK PRIMARY KEY (ID)
);

CREATE TABLE GO.TERM_R
(
  ID INTEGER NOT NULL,
  NAME VARCHAR(255),
  ACC VARCHAR(255),
  CONSTRAINT TERM_PK PRIMARY KEY (ID)
);