
CREATE SCHEMA INTERPRO;

CREATE TABLE INTERPRO.ENTRY 
    (
     ENTRY_AC VARCHAR(9) NOT NULL, 
     NAME VARCHAR(100),
     CONSTRAINT ENTRY_PK PRIMARY KEY (ENTRY_AC)
     );
     

CREATE TABLE INTERPRO.ENTRY2METH 
   (
     ENTRY_AC VARCHAR(9) NOT NULL, 
     METHOD_AC VARCHAR(25) NOT NULL,
     DB VARCHAR(20) NOT NULL,
     CONSTRAINT ENTRY2METH_PK PRIMARY KEY (ENTRY_AC, DB, METHOD_AC)
    );
    
CREATE TABLE INTERPRO.INTERPRO2GO 
    (
     ENTRY_AC VARCHAR(9) NOT NULL, 
     GO_AC    VARCHAR(10) NOT NULL,
     CONSTRAINT INTERPRO2GO_PK PRIMARY KEY (ENTRY_AC, GO_AC)
    );
    
    
CREATE TABLE INTERPRO.ENTRY_L
    (
     ENTRY_AC VARCHAR(9) NOT NULL, 
     NAME VARCHAR(100),
     CONSTRAINT ENTRY_PK PRIMARY KEY (ENTRY_AC)
     );     
     
CREATE TABLE INTERPRO.ENTRY_R
    (
     ENTRY_AC VARCHAR(9) NOT NULL, 
     NAME VARCHAR(100),
     CONSTRAINT ENTRY_PK PRIMARY KEY (ENTRY_AC)
     );          
     
CREATE TABLE INTERPRO.ENTRY2METH_L
   (
     ENTRY_AC VARCHAR(9) NOT NULL, 
     METHOD_AC VARCHAR(25) NOT NULL,
     DB VARCHAR(20) NOT NULL,
     CONSTRAINT ENTRY2METH_PK PRIMARY KEY (ENTRY_AC, DB, METHOD_AC)
    ); 
    
CREATE TABLE INTERPRO.ENTRY2METH_R
   (
     ENTRY_AC VARCHAR(9) NOT NULL, 
     METHOD_AC VARCHAR(25) NOT NULL,
     DB VARCHAR(20) NOT NULL,
     CONSTRAINT ENTRY2METH_PK PRIMARY KEY (ENTRY_AC, DB, METHOD_AC)
    );    
    
CREATE TABLE INTERPRO.INTERPRO2GO_L 
    (
     ENTRY_AC VARCHAR(9) NOT NULL, 
     GO_AC    VARCHAR(10) NOT NULL,
     CONSTRAINT INTERPRO2GO_PK PRIMARY KEY (ENTRY_AC, GO_AC)
    );       
    
CREATE TABLE INTERPRO.INTERPRO2GO_R
    (
     ENTRY_AC VARCHAR(9) NOT NULL, 
     GO_AC    VARCHAR(10) NOT NULL,
     CONSTRAINT INTERPRO2GO_PK PRIMARY KEY (ENTRY_AC, GO_AC)
    );    