
CREATE SCHEMA PLASMO;

CREATE TABLE PLASMO.GENEFEAT
(
	SRC_ID  VARCHAR(50) NOT NULL, 
	PRODUCT VARCHAR(4000), 
	REFSEQ_ACC VARCHAR(100), 	
	CONSTRAINT GENEFEAT_PK PRIMARY KEY (SRC_ID)
);

CREATE TABLE PLASMO.REFSEQ
(
  GI INTEGER NOT NULL,
  ACC VARCHAR(100),
  SEQ VARCHAR (500),
  PL  DOUBLE,
  DEPRECATED VARCHAR(3),
  CONSTRAINT REFSEQ_PK PRIMARY KEY (GI)
);

CREATE TABLE PLASMO.GENETAX 
(
 SRC_ID VARCHAR(50) NOT NULL,
 TAX_ID  INTEGER NOT NULL,
 CONSTRAINT GENETAX_PK PRIMARY KEY (SRC_ID, TAX_ID) 
);

CREATE TABLE PLASMO.TAXNAMES
(
 TAX_ID  INTEGER NOT NULL, 
 TAX_NAME VARCHAR(255) NOT NULL, 
 NAME_CLASS VARCHAR(300) NOT NULL,
 CONSTRAINT TAXNAMES_PK PRIMARY KEY (TAX_ID, TAX_NAME, NAME_CLASS) 
);
 
	
CREATE TABLE PLASMO.DOMAIN_REF
(
  SRC_ID  VARCHAR(50) NOT NULL, 
  DB VARCHAR(80) NOT NULL, 
  DBACC VARCHAR(100)  NOT NULL,
  CONSTRAINT DOMAIN_REF_PK PRIMARY KEY (SRC_ID, DB, DBACC)
);


CREATE TABLE PLASMO.GOTERM_SUMMARY
(
 SRC_ID  VARCHAR(50) NOT NULL, 
 GO_ID VARCHAR(32) NOT NULL,
 SOURCE VARCHAR(80),
 CONSTRAINT GOTERM_SUMMARY_PK PRIMARY KEY (SRC_ID, GO_ID)
);

CREATE TABLE PLASMO.GOTERM
(
 GO_ID VARCHAR(32) NOT NULL, 
 GO_NAME VARCHAR(255), 
 CONSTRAINT GOTERM_SUMMARY_PK PRIMARY KEY (GO_ID)
);



CREATE TABLE PLASMO.GENEFEAT_L
(
	SRC_ID  VARCHAR(50) NOT NULL, 
	PRODUCT VARCHAR(4000), 
	REFSEQ_ACC VARCHAR(100), 
	CONSTRAINT GENEFEAT_PK PRIMARY KEY (SRC_ID)
);

CREATE TABLE PLASMO.GENEFEAT_R
(
	SRC_ID  VARCHAR(50) NOT NULL, 
	PRODUCT VARCHAR(4000), 
	REFSEQ_ACC VARCHAR(100), 
	CONSTRAINT GENEFEAT_PK PRIMARY KEY (SRC_ID)
);

CREATE TABLE PLASMO.REFSEQ_L
(
  GI INTEGER NOT NULL,
  ACC VARCHAR(100),
  SEQ VARCHAR (500),
  PL  DOUBLE,  
  DEPRECATED VARCHAR(3),
  CONSTRAINT REFSEQ_PK PRIMARY KEY (GI)
);

CREATE TABLE PLASMO.REFSEQ_R
(
  GI INTEGER NOT NULL,
  ACC VARCHAR(100),
  SEQ VARCHAR (500),
  PL  DOUBLE,  
  DEPRECATED VARCHAR(3),
  CONSTRAINT REFSEQ_PK PRIMARY KEY (GI)
);

CREATE TABLE PLASMO.GENETAX_L
(
 SRC_ID VARCHAR(50) NOT NULL,
 TAX_ID  INTEGER NOT NULL, 
 CONSTRAINT GENETAX_PK PRIMARY KEY (SRC_ID, TAX_ID) 
);

CREATE TABLE PLASMO.GENETAX_R
(
 SRC_ID VARCHAR(50) NOT NULL,
 TAX_ID  INTEGER NOT NULL, 
 CONSTRAINT GENETAX_PK PRIMARY KEY (SRC_ID, TAX_ID) 
);

CREATE TABLE PLASMO.TAXNAMES_L
(
 TAX_ID  INTEGER NOT NULL, 
 TAX_NAME VARCHAR(255) NOT NULL, 
 NAME_CLASS VARCHAR(300) NOT NULL,
 CONSTRAINT TAXNAMES_PK PRIMARY KEY (TAX_ID, TAX_NAME, NAME_CLASS) 
);

CREATE TABLE PLASMO.TAXNAMES_R
(
 TAX_ID  INTEGER NOT NULL, 
 TAX_NAME VARCHAR(255) NOT NULL, 
 NAME_CLASS VARCHAR(300) NOT NULL,
 CONSTRAINT TAXNAMES_PK PRIMARY KEY (TAX_ID, TAX_NAME, NAME_CLASS) 
);



CREATE TABLE PLASMO.DOMAIN_REF_L
(
  SRC_ID  VARCHAR(50) NOT NULL, 
  DB VARCHAR(80) NOT NULL, 
  DBACC VARCHAR(100)  NOT NULL,
  CONSTRAINT DOMAIN_REF_PK PRIMARY KEY (SRC_ID, DB, DBACC)
);

CREATE TABLE PLASMO.DOMAIN_REF_R
(
  SRC_ID  VARCHAR(50) NOT NULL, 
  DB VARCHAR(80) NOT NULL, 
  DBACC VARCHAR(100)  NOT NULL,
  CONSTRAINT DOMAIN_REF_PK PRIMARY KEY (SRC_ID, DB, DBACC)
);


CREATE TABLE PLASMO.GOTERM_SUMMARY_L
(
 SRC_ID  VARCHAR(50) NOT NULL, 
 GO_ID VARCHAR(32) NOT NULL, 
 SOURCE VARCHAR(80),
 CONSTRAINT GOTERM_SUMMARY_PK PRIMARY KEY (SRC_ID, GO_ID)
);


CREATE TABLE PLASMO.GOTERM_SUMMARY_R
(
 SRC_ID  VARCHAR(50) NOT NULL, 
 GO_ID VARCHAR(32) NOT NULL, 
 SOURCE VARCHAR(80),
 CONSTRAINT GOTERM_SUMMARY_PK PRIMARY KEY (SRC_ID, GO_ID)
);


CREATE TABLE PLASMO.GOTERM_L
(
 GO_ID VARCHAR(32) NOT NULL, 
 GO_NAME VARCHAR(255), 
 CONSTRAINT GOTERM_SUMMARY_PK PRIMARY KEY (GO_ID)
);

CREATE TABLE PLASMO.GOTERM_R
(
 GO_ID VARCHAR(32) NOT NULL, 
 GO_NAME VARCHAR(255), 
 CONSTRAINT GOTERM_SUMMARY_PK PRIMARY KEY (GO_ID)
);

