
CREATE SCHEMA APPLYSCHEMA ;


CREATE TABLE "APPLYSCHEMA"."APPLYRELATION_L"  (
		  "RID" INTEGER , 
		  "RSTR" VARCHAR(10) , 
		  "RSTR_LN" INTEGER NOT NULL WITH DEFAULT 1 )   
		 IN "USERSPACE1" ; 


CREATE TABLE "APPLYSCHEMA"."APPLYRELATION_R"  (
		  "RID" INTEGER , 
		  "RSTR" VARCHAR(10) , 
		  "RSTR_LN" INTEGER NOT NULL WITH DEFAULT 1 )   
		 IN "USERSPACE1" ; 


CREATE TABLE "APPLYSCHEMA"."APPLYRELATION_L_INS"  (
		  "RID" INTEGER , 
		  "RSTR" VARCHAR(10) , 
		  "RSTR_LN" INTEGER NOT NULL WITH DEFAULT 1 )   
		 IN "USERSPACE1" ; 


CREATE TABLE "APPLYSCHEMA"."APPLYRELATION_L_DEL"  (
		  "RID" INTEGER , 
		  "RSTR" VARCHAR(10) , 
		  "RSTR_LN" INTEGER NOT NULL WITH DEFAULT 1 )   
		 IN "USERSPACE1" ; 



CREATE TABLE "APPLYSCHEMA"."APPLYRELATION_R_DEL"  (
		  "RID" INTEGER , 
		  "RSTR" VARCHAR(10) , 
		  "RSTR_LN" INTEGER NOT NULL WITH DEFAULT 1 )   
		 IN "USERSPACE1" ; 


CREATE TABLE "APPLYSCHEMA"."APPLYRELATION_R_INS"  (
		  "RID" INTEGER , 
		  "RSTR" VARCHAR(10) , 
		  "RSTR_LN" INTEGER NOT NULL WITH DEFAULT 1 )   
		 IN "USERSPACE1" ; 



CREATE TABLE "APPLYSCHEMA"."APPLYRELATION"  (
		  "RID" INTEGER NOT NULL , 
		  "RSTR" VARCHAR(10) , 
		  "RSTR_LN" INTEGER NOT NULL WITH DEFAULT 1 )   
		 IN "USERSPACE1" ; 


ALTER TABLE "APPLYSCHEMA"."APPLYRELATION" 
	ADD CONSTRAINT "APPLYRELATION_PK" PRIMARY KEY
		("RID");


